name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 8
          - 10
          - 12
          - 13
          - 14
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - name: Upload coverage
        if: success()
        run:
          curl -s https://codecov.io/bash | bash -s - -f coverage/lcov.info -n
          "Node.js ${{ matrix.node }} on ${{ matrix.os }}"
        shell: bash
